####################################################################
#
# export HF_HOME=${local_path_you_want}
# hf download unsloth/Qwen3.8-27B-GGUF Qwen3.8-27B-UD-Q4_K_XL.gguf
# for mtp need 26GB vRam
#--spec-type draft-mtp
#--spec-draft-n-max 2
#--spec-draft-type-k q4_0
#--spec-draft-type-v q4_0
#--parallel 1
####################################################################

services:
  llama-server:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    container_name: llama-qwen3.8-27b
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0','1']
              capabilities: [gpu]
    ipc: host
    ports:
      - "${VLLM_API_PORT}:8000"
    environment:
      - HF_HOME=${HF_HOME}
    volumes:
      - ./models:${HF_HOME}
    command: >
      -m ${HF_HOME}/hub/models--unsloth--Qwen3.8-27B-GGUF/snapshots/f1bfb127c64f7072bdd2cad55f258b9c8b2910fe/Qwen3.8-27B-UD-Q4_K_XL.gguf
      -ts 1,1
      -ngl 99
      -fa auto
      --ctx-size 131072
      --cache-type-k q8_0
      --cache-type-v q8_0
      -np 1
      --spec-draft-n-max 2
      --parallel 1
      --temp 1.0
      --top-p 0.95
      --top-k 20
      --min-p 0.0
      --repeat-penalty 1.0
      --presence-penalty 0.0
      --chat-template-kwargs '{"reasoning_effort":"xhigh"}'
      --jinja
      --reasoning-format deepseek
      --alias Qwen3.8-27B-UD-Q4_K_M
      --host 0.0.0.0
      --port 8000
    restart: unless-stopped

